---
title: 平成28年1月1日住民基本台帳 都道府県別人口
author: "Asset Management Consulting Corporation / アセット･マネジメント･コンサルティング株式会社 http://am-consulting.co.jp"
output:
  html_document:
    fig_height: 10
    fig_width: 10
    keep_md: no
---
Data Source:総務省  
作成日
```{r,warning=F,error=F,message=F,results='hold',echo=F}
Sys.time()
```

```{r,warning=F,error=F,message=F,echo=F}
library(DT)
```
---
```{r,warning=F,error=F,message=F,echo=F}
title<-"平成28年1月1日住民基本台帳 都道府県別人口"
tmp <-
  read.table(
    "clipboard",
    header = TRUE,
    sep = "\t",
    stringsAsFactor = F,
    na.strings = c("na", ""),
    check.names = F
  )
dataSet <- data.frame(ID = seq(1, nrow(tmp)), tmp, check.names = F)
funDT <- function() {
  DT::datatable(
    dataSet,
    options = list(
      search.regex = T,
      paging = T,
      autoWidth = T,
      info = T,
      lengthChange = T,
      ordering = T,
      searching = T,
      scrollX = T,
      lengthMenu = list(c(20,-1, 10, 1), c("20","All","10", 1)),
      orderClasses = T,
      order = list(list(0, "asc"))
    ), 
    rownames = F,
    caption = title,
    class = "display compact"
  )
}
```

```{r,warning=F,error=F,message=F,results='asis',echo=F}
funDT()
```